version: '2.1'

services:

  server:
    restart: on-failure
    entrypoint: php artisan serve --host=0.0.0.0
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  migrations:
    build:
      context: .
    entrypoint: bash -c "php artisan migrate && php artisan db:seed"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mysql:5.7.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-uuser", "-proot", "laravel", "-e", "exit"]
      interval: 10s
      timeout: 5s
      retries: 5
